// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Ahorcado;

import Ahorcado.Partida;

/************************************************************/
/**
 * 
 */
public class Horca {
	/**
	 * es el número de fallos que lleva el usuario, vamos a permitir 6 fallos
	 */
	private int fallos;
	/**
	 * 
	 */
	public Partida partida;

	/**
	 * 
	 */
	public void dibujar() {
	}

	/**
	 * incrementa el contador de fallos
	 */
	public void incrementarFallo() {
	}

	/**
	 * comprueba si hemos perdido la partida
	 * @return perdido 
	 */
	public boolean comprobarSiPerdido() {
	}
};
