// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Ahorcado;

import Ahorcado.Partida;

/************************************************************/
/**
 * 
 */
public class Palabra {
	/**
	 * 
	 */
	private String palabraOculta;
	/**
	 * son las letras que el jugador ha acertado
	 */
	private char[] letrasDescubiertas;
	/**
	 * son las letras que el jugador ha dicho pero no estaban en la palabra
	 */
	private char[] letrasFallidas;
	/**
	 * 
	 */
	public Partida partida;

	/**
	 * 
	 */
	public void elegirPalabra() {
	}

	/**
	 * comprueba si letra está en la palabra oculta
	 * @param letra es la letra a comprobar si está en la palabra a adivinar
	 * @return estaba devuelve verdadero si la letra está al menos una vez en la palabra y falso en caso contrario
	 */
	public boolean comprobarLetra(char letra) {
	}

	/**
	 * mostramos el estado de la palabra, las letras acertadas y las letras fallidas
	 */
	public void mostrarResultados() {
	}

	/**
	 * comprueba si hemos acertado todas las letras
	 * @return ganado 
	 */
	public boolean comprobarSiGanado() {
	}

	/**
	 * comprueba si la palabra propuesta por el jugador coincide con la palabra oculta (quiero resolver)
	 * @param palabra 
	 * @return adivinada adivinada es verdadero si la palabra coincide con la que buscábamos
	 */
	public boolean comprobarPalabra(String palabra) {
	}
};
