// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Ahorcado;

/************************************************************/
/**
 * 
 */
public class Palabra {
	/**
	 * 
	 */
	private String palabraOculta;
	/**
	 * son las letras que el jugador ha acertado
	 */
	private char[] letrasDescubiertas;
	/**
	 * son las letras que el jugador ha dicho pero no estaban en la palabra
	 */
	private char[] letrasFallidas;

	/**
	 * 
	 */
	public String elegirPalabra() {
		String[] palabras = {"Jirafa", "Perro", "Gato", "Gallo", "Elefante","Rata","Tortuga"};
		String elegida = palabras[(int) (Math.round(Math.random() * (palabras.length-1)))];	
		return elegida;
	}

	/**
	 * comprueba si letra está en la palabra oculta
	 * @param letra es la letra a comprobar si está en la palabra a adivinar
	 * @return estaba devuelve verdadero si la letra está al menos una vez en la palabra y falso en caso contrario
	 */
	public boolean comprobarLetra(char letra) {
		if (palabraOculta.indexOf(letra)==-1) return false;
		else return true;
	}

	/**
	 * mostramos el estado de la palabra, las letras acertadas y las letras fallidas
	 */
	public void mostrarResultados() {
	}

	/**
	 * comprueba si hemos acertado todas las letras
	 * @return ganado 
	 */
	public boolean comprobarSiGanado() {
	}

	/**
	 * comprueba si la palabra propuesta por el jugador coincide con la palabra oculta (quiero resolver)
	 * @param palabra 
	 * @return adivinada adivinada es verdadero si la palabra coincide con la que buscábamos
	 */
	public boolean comprobarPalabra(String palabra) {
	}
};
