// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Ahorcado;

/************************************************************/
/**
 * 
 */
public class Partida {

	/**
	 * 
	 */
	public void mostrarProgreso() {
	}

	/**
	 * 
	 * @return letra 
	 */
	public char pedirLetra() {
	}

	/**
	 * 
	 */
	public void resolver() {
	}

	/**
	 * 
	 * @return fin 
	 */
	public boolean comprobarFinal() {
	}
};
